# NumPy - start

NumPy jest biblioteką Pythona służącą do obliczeń naukowych.

Zastosowania:
  
* algebra liniowa
* zaawansowane obliczenia matematyczne (numeryczne)
* całkowanie numeryczne
* rozwiązywanie równań



## Import biblioteki NumPy

```python
import numpy as np
```

Podstawowym obiektem w bibliotece NumPy jest N-wymiarowa tablica zwana `ndarray`. Podstawowym obiektem w bibliotece NumPy jest N-wymiarowa tablica zwana `ndarray`. Każdy element tablicy traktowany jest jako typ `dtype`.


```python
np.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```

* object - obiekt (lub sekwencja), który ma zostać przekształcony w tablicę
* dtype - typ
* copy - czy obiekty mają być skopiowane, domyślnie `True`
* order - sposób układania: C (rzędy),  F (kolumny), A, K
* subok - realizowane przez podklasy (jeśli `True`), domyślnie `False`
* ndmin - minimalny rozmiar (wymiar) tablicy
* like - tworzenie na podstawie tablicy referencyjnej



```{python}
#| echo: true
import numpy as np

a = np.array([1, 2, 3])    # <1>                           
print("a:", a) 
print("typ a:", type(a))  # <2>
b = np.array([1, 2, 3.0]) # <3>
print("b:", b)
c = np.array([[1, 2], [3, 4]]) # <4>
print("c:", c)
d = np.array([1, 2, 3], ndmin=2) # <5>
print("d:", d)
e = np.array([1, 2, 3], dtype=complex) # <6>
print("e:", e)
f = np.array(np.asmatrix('1 2; 3 4')) # <7>
print("f:", f)
g = np.array(np.asmatrix('1 2; 3 4'), subok=True) # <8>
print("g:", g)
print(type(g))

```

1. Tworzenie tablicy z domyślnymi ustawieniami.
2. Sprawdzenie typu.
3. Jeden z elementów jest innego typu. Tu następuje zatem rozszerzenie do typu "największego".
4. Tu otrzymamy tablicę 2x2.
5. W tej linijce otrzymamy tablicę o wymiarach 1x3 (kształt `(1, 3)`).
6. Wymuszenie typu `complex` - typu o szerszym zakresie.
7. Skorzystanie z podtypu macierzowego.
8. Zachowanie typu macierzowego.
